wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720169481
    t:
      1:
      - 1
      - 2
      - 3
      - 9
      - 11
      - 12
      - 41
      - 45
      - 49
      - 55
      - 103
      2:
      - 1
      - 2
      - 3
      - 9
      - 11
      - 12
      - 41
      - 45
      - 49
      - 55
      - 103
      3:
      - 13
      - 23
      4: 3.11.9
      5: 0.17.3
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
